### ISSUE TITLE
Cannot compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [linuxdeepin/dtkwidget#14]
Cannot compile on Ubuntu 14.04:

```
$ qmake .. CONFIG+=release PREFIX=/usr
Info: creating stash file /home/travis/build/probonopd/dtkwidget/build/.qmake.stash
/home/travis/build/probonopd/dtkwidget/dtkwidget.pro:1: Cannot find feature dtk_lib
The command "qmake .. CONFIG+=release PREFIX=/usr" exited with 0.
0.11s$ make -j$(nproc)
g++ -Wl,-O1 -Wl,-rpath,/opt/qt59/lib -o dtkwidget    -L/opt/qt59/lib -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [dtkwidget] Error 1
The command "make -j$(nproc)" exited with 2.
```

Build steps:
https://github.com/probonopd/dtkwidget/blob/f6e5ecc8a182c30a2761cdc813f999fbb7a8a942/.travis.yml

Build log:
https://travis-ci.com/probonopd/dtkwidget/builds/95890600#L534-L545

cc @rekols

**Comment by rekols** [comment]
I have time to try it.

**Comment by JackLovel** [comment]
I get same question

**Comment by probonopd** [comment]
Thank you. With Ubuntu 14.04 being EOL in April, I think we can relax the requirement now and focus on 16.04, if this makes it easier. Thanks.
